create table LOYALTY_SURVEY
(
  ID TBIGIDENT not null,
  CREATEDATE timestamp not null,
  DCODE TBIGCODE not null,
  DOCRATE varchar(50) not null,
  COMMENTARY TTEXT1024,
  PHONE varchar(10),
  CL_RECOMMEND varchar(50),
  PHOTO_PATH TTEXT512,
  FILIAL integer not null,
  REPL$ID TICODE not null,
  REPL$GRPID TICODE not null,
  DEPNUM integer,
  EM_ANGER numeric(8,3),
  EM_CONTEMPT numeric(8,3),
  EM_DISGUST numeric(8,3),
  EM_FEAR numeric(8,3),
  EM_HAPPINESS numeric(8,3),
  EM_NEUTRAL numeric(8,3),
  EM_SADNESS numeric(8,3),
  EM_SURPRICE numeric(8,3),
  constraint PK_LOYALTY_SURVEY primary key (ID)
);

create index DCODE_FILIAL on LOYALTY_SURVEY(DCODE, FILIAL);
create index DATE_IDX on LOYALTY_SURVEY(CREATEDATE);
create unique index REPL$LOYALTY_SURVEY_IDX on LOYALTY_SURVEY(REPL$ID, REPL$GRPID);
CREATE GENERATOR LOYALTY_SURVEY_GEN;

create or alter trigger LOYALTY_SURVEY_BI for LOYALTY_SURVEY
active before insert position 0
AS
    BEGIN
      IF ((USER <> 'REPL') AND (CURRENT_ROLE <> 'REPL')) THEN
      BEGIN
        IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(LOYALTY_SURVEY_GEN, 1);

        IF (NEW.CREATEDATE IS NULL) THEN
        NEW.CREATEDATE = 'now';

        IF (NEW.FILIAL IS NULL) THEN
        SELECT REPL$GRPID FROM REPL$GETGRPID INTO NEW.FILIAL;

        IF (NEW.REPL$ID IS NULL) THEN
        NEW.REPL$ID = GEN_ID(REPL$LOYALTY_SURVEY_GEN,1);

        IF (NEW.REPL$GRPID IS NULL) THEN
        SELECT REPL$GRPID FROM REPL$GETGRPID INTO NEW.REPL$GRPID;
      END
    END;

create or alter trigger REPL$LOYALTY_SURVEY_AI for LOYALTY_SURVEY
active after insert position 0
AS
    BEGIN
      IF (EXISTS(SELECT * FROM REPL$GETACCESS WHERE REPL$ACCESS = 'REPL')) THEN
    BEGIN
      INSERT INTO REPL$CHANGELOG (TABLENAME, REPLID, REPLGRPID, OP)
      VALUES ('LOYALTY_SURVEY', NEW.REPL$ID, NEW.REPL$GRPID, 0);
  END
END;

create or alter trigger REPL$LOYALTY_SURVEY_AU for LOYALTY_SURVEY
active after update position 0
AS
BEGIN
  IF (EXISTS(SELECT * FROM REPL$GETACCESS WHERE REPL$ACCESS = 'REPL')) THEN
  BEGIN
    INSERT INTO REPL$CHANGELOG (TABLENAME, REPLID, REPLGRPID, OP)
    VALUES ('LOYALTY_SURVEY', NEW.REPL$ID, NEW.REPL$GRPID, 1);
  END
END;

create or alter trigger REPL$LOYALTY_SURVEY_AD for LOYALTY_SURVEY
active after delete position 0
AS
BEGIN
  IF (EXISTS(SELECT * FROM REPL$GETACCESS WHERE REPL$ACCESS = 'REPL')) THEN
  BEGIN
    INSERT INTO REPL$CHANGELOG (TABLENAME, REPLID, REPLGRPID, OP)
    VALUES ('LOYALTY_SURVEY', OLD.REPL$ID, OLD.REPL$GRPID, 2);
  END
END;