//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfoKiosk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfoKiosk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BackButton {
            get {
                object obj = ResourceManager.GetObject("BackButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonBackspace {
            get {
                object obj = ResourceManager.GetObject("ButtonBackspace", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonCapslock {
            get {
                object obj = ResourceManager.GetObject("ButtonCapslock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClear {
            get {
                object obj = ResourceManager.GetObject("ButtonClear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonClose {
            get {
                object obj = ResourceManager.GetObject("ButtonClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonLeft {
            get {
                object obj = ResourceManager.GetObject("ButtonLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonOk {
            get {
                object obj = ResourceManager.GetObject("ButtonOk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonRight {
            get {
                object obj = ResourceManager.GetObject("ButtonRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonSearch {
            get {
                object obj = ResourceManager.GetObject("ButtonSearch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftPressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftPressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ButtonShiftUnpressed {
            get {
                object obj = ResourceManager.GetObject("ButtonShiftUnpressed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DoctorWithoutAPhoto {
            get {
                object obj = ResourceManager.GetObject("DoctorWithoutAPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DownButton {
            get {
                object obj = ResourceManager.GetObject("DownButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_angry {
            get {
                object obj = ResourceManager.GetObject("smile_angry", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_happy {
            get {
                object obj = ResourceManager.GetObject("smile_happy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_love {
            get {
                object obj = ResourceManager.GetObject("smile_love", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_neutral {
            get {
                object obj = ResourceManager.GetObject("smile_neutral", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smile_sad {
            get {
                object obj = ResourceManager.GetObject("smile_sad", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый клинический медицинский центр - многопрофильная негосударственная клиника принципиально нового, уникального для России формата, в основе которого - использование передовых мировых технологий и стандартов, новейшего оборудования. 
        ///
        ///Центр является объединяющей платформой для реализации прорывных идей и методов на стыке фундаментальных медицинских исследований, медицинских технологий, умного медицинского оборудования и медицинских услуг, преимущественно, высокотехнологичной медицинской помощи. 
        ///
        ///Пер [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringContactsLeftPart {
            get {
                return ResourceManager.GetString("StringContactsLeftPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аптека
        ///Пн-Суб: с 8:00 до 21:00
        ///
        ///Поликлиника и дневной стационар:
        ///8.00-21.00 пн-пт, 9-15 сб, Вс выходной
        ///
        ///Хирургический стационар:
        ///Круглосуточно
        ///
        ///Адрес: 601900 Владимирская область, город Ковров, улица Ватутина 90
        ///
        ///Контактный телефон: 8-800-222-95-53
        ///
        ///Представительство Первого клинического медицинского центра в г. Москва: 8-495-937-50-50
        ///Астафьева Елена (персональный менеджер) - 8-926-706-01-07
        ///
        ///Перова Анна (персональный менеджер) - 8-916-430-71-17
        ///
        ///
        ///Почта:
        ///info@clinicalcenter.ru
        ///
        ///Офици [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StringContactsRightPart {
            get {
                return ResourceManager.GetString("StringContactsRightPart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string StringRateDoctorMark1 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string StringRateDoctorMark2 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string StringRateDoctorMark3 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string StringRateDoctorMark4 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string StringRateDoctorMark5 {
            get {
                return ResourceManager.GetString("StringRateDoctorMark5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnknownDepartment {
            get {
                object obj = ResourceManager.GetObject("UnknownDepartment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UpButton {
            get {
                object obj = ResourceManager.GetObject("UpButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
